import { AppLanguage } from "../middleware";

export const supportedLanguages = {
  [AppLanguage.English]: {
    code: AppLanguage.English,
    name: "English",
    shortName: "EN",
    direction: "ltr",
    isLeftDirection: true,
    locale: "en-EN",
  },
  [AppLanguage.Arabic]: {
    code: AppLanguage.Arabic,
    name: "العربية",
    shortName: "عربي",
    direction: "rtl",
    isLeftDirection: false,
    font: "font-kufi",
    locale: "ar-AE",
  },
  [AppLanguage.Pashto]: {
    code: AppLanguage.Pashto,
    name: "پښتو",
    shortName: "پښتو",
    direction: "rtl",
    isLeftDirection: false,
    locale: "ps-AF",
  },
  [AppLanguage.korean]: {
    code: AppLanguage.korean,
    name: "한국어",
    shortName: "한국어",
    direction: "ltr",
    isLeftDirection: true,
    locale: "ko-KR",
  },
  [AppLanguage.Farsi]: {
    code: AppLanguage.Farsi,
    name: "فارسی",
    shortName: "فا",
    direction: "rtl",
    isLeftDirection: false,
    font: "font-kufi",
    locale: "fa-IR",
  },
  [AppLanguage.Chinese]: {
    code: AppLanguage.Chinese,
    name: "中文",
    shortName: "中",
    direction: "ltr",
    isLeftDirection: true,
    locale: "zh-hans",
  },
  [AppLanguage.Italian]: {
    code: AppLanguage.Italian,
    name: "Italiano",
    shortName: "IT",
    direction: "ltr",
    isLeftDirection: true,
    locale: "it-IT",
  },
  [AppLanguage.Melayu]: {
    code: AppLanguage.Melayu,
    name: "Melayu",
    shortName: "MY",
    direction: "ltr",
    isLeftDirection: true,
    locale: "ms-MY",
  },
  [AppLanguage.Hindi]: {
    code: AppLanguage.Hindi,
    name: "हिन्दी",
    shortName: "हि",
    direction: "ltr",
    isLeftDirection: true,
    locale: "hi-IN",
  },
  [AppLanguage.Indonasian]: {
    code: AppLanguage.Indonasian,
    name: "Bahasa Indonesia",
    shortName: "ID",
    direction: "ltr",
    isLeftDirection: true,
    locale: "id-ID",
  },
  [AppLanguage.French]: {
    code: AppLanguage.French,
    name: "Français",
    shortName: "FR",
    direction: "ltr",
    isLeftDirection: true,
    locale: "fr-FR",
  },
  [AppLanguage.Spanish]: {
    code: AppLanguage.Spanish,
    name: "Español",
    shortName: "ES",
    direction: "ltr",
    isLeftDirection: true,
    locale: "es-ES",
  },
  [AppLanguage.Japanese]: {
    code: AppLanguage.Japanese,
    name: "日本語",
    shortName: "JP",
    direction: "ltr",
    isLeftDirection: true,
    locale: "ja-JP",
  },
  [AppLanguage.Vitenam]: {
    code: AppLanguage.Vitenam,
    name: "Tiếng Việt",
    shortName: "VI",
    direction: "ltr",
    isLeftDirection: true,
    locale: "vi-VN",
  },
  [AppLanguage.Philippines]: {
    code: AppLanguage.Philippines,
    name: "Tagalog",
    shortName: "tl-PH",
    direction: "ltr",
    isLeftDirection: true,
    locale: "tl-PH",
  },
  [AppLanguage.Urdu]: {
    code: AppLanguage.Urdu,
    name: "Urdu",
    shortName: "ur",
    direction: "rtl",
    isLeftDirection: false,
    font: "font-kufi",
    locale: "ur-PK",
  },
  [AppLanguage.português]: {
    code: AppLanguage.português,
    name: "Português",
    shortName: "pt-PT",
    direction: "ltr",
    isLeftDirection: true,
    locale: "pt-PT",
  },
  [AppLanguage.Thailand]: {
    code: AppLanguage.Thailand,
    name: "ไทย",
    shortName: "th-TH",
    direction: "ltr",
    isLeftDirection: true,
    locale: "th-TH",
  },
  [AppLanguage.Chinese_Traditional]: {
    code: AppLanguage.Chinese_Traditional,
    name: "繁體中文",
    shortName: "zh-TW",
    direction: "ltr",
    isLeftDirection: true,
    locale: "zh-TW",
  },
  [AppLanguage.Russian]: {
    code: AppLanguage.Russian,
    name: "Русский",
    shortName: "ru",
    direction: "ltr",
    isLeftDirection: true,
    locale: "ru-RU",
  },
};
